Return-Path: <baris.simsek@domain.com>
Delivered-To: simsek@bugsbunny.domain.com
Received: (qmail 7590 invoked from network); 5 Oct 2004 08:22:38 -0000
Received: from unknown (HELO mail.domain.com) (192.168.1.9)
  by 0 with SMTP; 5 Oct 2004 08:22:38 -0000
Received: (qmail 21376 invoked by uid 1010); 5 Oct 2004 07:26:37 -0000
Received: from unknown (HELO ?192.168.1.90?) (baris.simsek@192.168.1.90)
  by 0 with SMTP; 5 Oct 2004 07:26:37 -0000
Message-ID: <41624BEF.5060908@domain.com>
Date: Tue, 05 Oct 2004 10:23:27 +0300
From: Baris Simsek <baris.simsek@domain.com>
User-Agent: Mozilla Thunderbird 0.8 (Windows/20040913)
X-Accept-Language: en-us, en
MIME-Version: 1.0
To: baris.simsek@endersys.com
Subject: attached file is containing EICAR test virus.
Content-Type: multipart/mixed;
 boundary="------------020601080201010008050006"

This is a multi-part message in MIME format.
--------------020601080201010008050006
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

Attached file contains EICAR virus test pattern.

Baris Simsek
http://www.enderunix.org/simsek/


--------------020601080201010008050006
Content-Type: text/plain;
 name="eicar.com.txt"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename="eicar.com.txt"

X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
--------------020601080201010008050006--
