Return-Path: <baris.simsek@domain.com>
Delivered-To: simsek@bugsbunny.domain.com
Received: (qmail 7590 invoked from network); 5 Oct 2004 08:22:38 -0000
Received: from unknown (HELO mail.domain.com) (192.168.1.9)
  by 0 with SMTP; 5 Oct 2004 08:22:38 -0000
Received: (qmail 21376 invoked by uid 1010); 5 Oct 2004 07:26:37 -0000
Received: from unknown (HELO ?192.168.1.90?) (baris.simsek@192.168.1.90)
  by 0 with SMTP; 5 Oct 2004 07:26:37 -0000
Message-ID: <41624BEF.5060908@domain.com>
Date: Tue, 05 Oct 2004 10:23:27 +0300
From: Baris Simsek <baris.simsek@domain.com>
User-Agent: Mozilla Thunderbird 0.8 (Windows/20040913)
To: simsek@bugsbunny.enderunix.org
Subject: download free software

Do you like viagra?

This is an example spam word: S0ftware

Baris Simsek
http://www.enderunix.org/simsek/

